Spring:
  h2:
    console:
      enabled: true
      path: "/h2"
      
  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: "org.h2.Driver"
    
server:
  port: 8082
  servlet:
    context-path: "/api"
  
spring:
  jpa:
    show-sql: true
